// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wraper.proto

package com.ibrightech.eplayer.sdk.common.net.ws.pb;

public final class Wraper {
  private Wraper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string event = 1;
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    boolean hasEvent();
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    String getEvent();
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    com.google.protobuf.ByteString
        getEventBytes();

    // required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];
    /**
     * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
     *
     * <pre>
     * message type
     * </pre>
     */
    boolean hasTp();
    /**
     * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
     *
     * <pre>
     * message type
     * </pre>
     */
    Msg.Type getTp();

    // repeated .com.soooner.ws.pb.Meta meta = 3;
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    java.util.List<Meta>
        getMetaList();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    Meta getMeta(int index);
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    int getMetaCount();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    java.util.List<? extends MetaOrBuilder>
        getMetaOrBuilderList();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    MetaOrBuilder getMetaOrBuilder(
            int index);

    // optional int32 userCount = 4;
    /**
     * <code>optional int32 userCount = 4;</code>
     */
    boolean hasUserCount();
    /**
     * <code>optional int32 userCount = 4;</code>
     */
    int getUserCount();
  }
  /**
   * Protobuf type {@code com.soooner.ws.pb.Msg}
   *
   * <pre>
   * bag id = 0
   * </pre>
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              event_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                tp_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                meta_ = new java.util.ArrayList<Meta>();
                mutable_bitField0_ |= 0x00000004;
              }
              meta_.add(input.readMessage(Meta.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              userCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          meta_ = java.util.Collections.unmodifiableList(meta_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wraper.internal_static_com_soooner_ws_pb_Msg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wraper.internal_static_com_soooner_ws_pb_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.soooner.ws.pb.Msg.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      /**
       * <code>CLIENT_EVENT = 1;</code>
       */
      CLIENT_EVENT(1, 1),
      /**
       * <code>USER_COUNT = 2;</code>
       */
      USER_COUNT(2, 2),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>CLIENT_EVENT = 1;</code>
       */
      public static final int CLIENT_EVENT_VALUE = 1;
      /**
       * <code>USER_COUNT = 2;</code>
       */
      public static final int USER_COUNT_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return CLIENT_EVENT;
          case 2: return USER_COUNT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Msg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.soooner.ws.pb.Msg.Type)
    }

    private int bitField0_;
    // required string event = 1;
    public static final int EVENT_FIELD_NUMBER = 1;
    private Object event_;
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    public String getEvent() {
      Object ref = event_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          event_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string event = 1;</code>
     *
     * <pre>
     *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEventBytes() {
      Object ref = event_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];
    public static final int TP_FIELD_NUMBER = 2;
    private Type tp_;
    /**
     * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
     *
     * <pre>
     * message type
     * </pre>
     */
    public boolean hasTp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
     *
     * <pre>
     * message type
     * </pre>
     */
    public Type getTp() {
      return tp_;
    }

    // repeated .com.soooner.ws.pb.Meta meta = 3;
    public static final int META_FIELD_NUMBER = 3;
    private java.util.List<Meta> meta_;
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    public java.util.List<Meta> getMetaList() {
      return meta_;
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    public java.util.List<? extends MetaOrBuilder>
        getMetaOrBuilderList() {
      return meta_;
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    public int getMetaCount() {
      return meta_.size();
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    public Meta getMeta(int index) {
      return meta_.get(index);
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
     */
    public MetaOrBuilder getMetaOrBuilder(
        int index) {
      return meta_.get(index);
    }

    // optional int32 userCount = 4;
    public static final int USERCOUNT_FIELD_NUMBER = 4;
    private int userCount_;
    /**
     * <code>optional int32 userCount = 4;</code>
     */
    public boolean hasUserCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 userCount = 4;</code>
     */
    public int getUserCount() {
      return userCount_;
    }

    private void initFields() {
      event_ = "";
      tp_ = Type.UNKNOWN;
      meta_ = java.util.Collections.emptyList();
      userCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEvent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMetaCount(); i++) {
        if (!getMeta(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEventBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, tp_.getNumber());
      }
      for (int i = 0; i < meta_.size(); i++) {
        output.writeMessage(3, meta_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, userCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEventBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, tp_.getNumber());
      }
      for (int i = 0; i < meta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, meta_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, userCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.soooner.ws.pb.Msg}
     *
     * <pre>
     * bag id = 0
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Wraper.internal_static_com_soooner_ws_pb_Msg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Wraper.internal_static_com_soooner_ws_pb_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.class, Builder.class);
      }

      // Construct using com.soooner.ws.pb.Wraper.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetaFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        event_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tp_ = Type.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          metaBuilder_.clear();
        }
        userCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Wraper.internal_static_com_soooner_ws_pb_Msg_descriptor;
      }

      public Msg getDefaultInstanceForType() {
        return Msg.getDefaultInstance();
      }

      public Msg build() {
        Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg buildPartial() {
        Msg result = new Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.event_ = event_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tp_ = tp_;
        if (metaBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            meta_ = java.util.Collections.unmodifiableList(meta_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userCount_ = userCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg) {
          return mergeFrom((Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg other) {
        if (other == Msg.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          bitField0_ |= 0x00000001;
          event_ = other.event_;
          onChanged();
        }
        if (other.hasTp()) {
          setTp(other.getTp());
        }
        if (metaBuilder_ == null) {
          if (!other.meta_.isEmpty()) {
            if (meta_.isEmpty()) {
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMetaIsMutable();
              meta_.addAll(other.meta_);
            }
            onChanged();
          }
        } else {
          if (!other.meta_.isEmpty()) {
            if (metaBuilder_.isEmpty()) {
              metaBuilder_.dispose();
              metaBuilder_ = null;
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000004);
              metaBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetaFieldBuilder() : null;
            } else {
              metaBuilder_.addAllMessages(other.meta_);
            }
          }
        }
        if (other.hasUserCount()) {
          setUserCount(other.getUserCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEvent()) {
          
          return false;
        }
        if (!hasTp()) {
          
          return false;
        }
        for (int i = 0; i < getMetaCount(); i++) {
          if (!getMeta(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string event = 1;
      private Object event_ = "";
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public String getEvent() {
        Object ref = event_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          event_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public Builder setEvent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      /**
       * <code>required string event = 1;</code>
       *
       * <pre>
       *"{msgType:xxxx, liveClassroomId:'abcdefg'}"
       * </pre>
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        event_ = value;
        onChanged();
        return this;
      }

      // required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];
      private Type tp_ = Type.UNKNOWN;
      /**
       * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
       *
       * <pre>
       * message type
       * </pre>
       */
      public boolean hasTp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
       *
       * <pre>
       * message type
       * </pre>
       */
      public Type getTp() {
        return tp_;
      }
      /**
       * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
       *
       * <pre>
       * message type
       * </pre>
       */
      public Builder setTp(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        tp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.soooner.ws.pb.Msg.Type tp = 2 [default = UNKNOWN];</code>
       *
       * <pre>
       * message type
       * </pre>
       */
      public Builder clearTp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tp_ = Type.UNKNOWN;
        onChanged();
        return this;
      }

      // repeated .com.soooner.ws.pb.Meta meta = 3;
      private java.util.List<Meta> meta_ =
        java.util.Collections.emptyList();
      private void ensureMetaIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          meta_ = new java.util.ArrayList<Meta>(meta_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Meta, Meta.Builder, MetaOrBuilder> metaBuilder_;

      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public java.util.List<Meta> getMetaList() {
        if (metaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(meta_);
        } else {
          return metaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public int getMetaCount() {
        if (metaBuilder_ == null) {
          return meta_.size();
        } else {
          return metaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Meta getMeta(int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);
        } else {
          return metaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder setMeta(
          int index, Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.set(index, value);
          onChanged();
        } else {
          metaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder setMeta(
          int index, Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.set(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder addMeta(Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(value);
          onChanged();
        } else {
          metaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder addMeta(
          int index, Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(index, value);
          onChanged();
        } else {
          metaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder addMeta(
          Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder addMeta(
          int index, Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder addAllMeta(
          Iterable<? extends Meta> values) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          super.addAll(values, meta_);
          onChanged();
        } else {
          metaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          metaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Builder removeMeta(int index) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.remove(index);
          onChanged();
        } else {
          metaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Meta.Builder getMetaBuilder(
          int index) {
        return getMetaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public MetaOrBuilder getMetaOrBuilder(
          int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);  } else {
          return metaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public java.util.List<? extends MetaOrBuilder>
           getMetaOrBuilderList() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(meta_);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Meta.Builder addMetaBuilder() {
        return getMetaFieldBuilder().addBuilder(
            Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public Meta.Builder addMetaBuilder(
          int index) {
        return getMetaFieldBuilder().addBuilder(
            index, Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 3;</code>
       */
      public java.util.List<Meta.Builder>
           getMetaBuilderList() {
        return getMetaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Meta, Meta.Builder, MetaOrBuilder>
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Meta, Meta.Builder, MetaOrBuilder>(
                  meta_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      // optional int32 userCount = 4;
      private int userCount_ ;
      /**
       * <code>optional int32 userCount = 4;</code>
       */
      public boolean hasUserCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 userCount = 4;</code>
       */
      public int getUserCount() {
        return userCount_;
      }
      /**
       * <code>optional int32 userCount = 4;</code>
       */
      public Builder setUserCount(int value) {
        bitField0_ |= 0x00000008;
        userCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userCount = 4;</code>
       */
      public Builder clearUserCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.soooner.ws.pb.Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.soooner.ws.pb.Msg)
  }

  public interface CmdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.soooner.ws.pb.Cmd.Type tp = 1;
    /**
     * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
     *
     * <pre>
     *type
     * </pre>
     */
    boolean hasTp();
    /**
     * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
     *
     * <pre>
     *type
     * </pre>
     */
    Cmd.Type getTp();

    // required int64 ct = 2;
    /**
     * <code>required int64 ct = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    boolean hasCt();
    /**
     * <code>required int64 ct = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    long getCt();

    // optional string txt = 3 [default = ""];
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    boolean hasTxt();
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    String getTxt();
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    com.google.protobuf.ByteString
        getTxtBytes();

    // repeated .com.soooner.ws.pb.Meta meta = 4;
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    java.util.List<Meta>
        getMetaList();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    Meta getMeta(int index);
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    int getMetaCount();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    java.util.List<? extends MetaOrBuilder>
        getMetaOrBuilderList();
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    MetaOrBuilder getMetaOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.soooner.ws.pb.Cmd}
   *
   * <pre>
   * bag id = 1
   * </pre>
   */
  public static final class Cmd extends
      com.google.protobuf.GeneratedMessage
      implements CmdOrBuilder {
    // Use Cmd.newBuilder() to construct.
    private Cmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cmd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cmd defaultInstance;
    public static Cmd getDefaultInstance() {
      return defaultInstance;
    }

    public Cmd getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                tp_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ct_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              txt_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                meta_ = new java.util.ArrayList<Meta>();
                mutable_bitField0_ |= 0x00000008;
              }
              meta_.add(input.readMessage(Meta.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          meta_ = java.util.Collections.unmodifiableList(meta_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wraper.internal_static_com_soooner_ws_pb_Cmd_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wraper.internal_static_com_soooner_ws_pb_Cmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Cmd.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Cmd> PARSER =
        new com.google.protobuf.AbstractParser<Cmd>() {
      public Cmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cmd(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Cmd> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.soooner.ws.pb.Cmd.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      /**
       * <code>HANDSHAKE = 1;</code>
       */
      HANDSHAKE(1, 1),
      /**
       * <code>PING = 2;</code>
       */
      PING(2, 2),
      /**
       * <code>PONG = 3;</code>
       */
      PONG(3, 3),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>HANDSHAKE = 1;</code>
       */
      public static final int HANDSHAKE_VALUE = 1;
      /**
       * <code>PING = 2;</code>
       */
      public static final int PING_VALUE = 2;
      /**
       * <code>PONG = 3;</code>
       */
      public static final int PONG_VALUE = 3;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return HANDSHAKE;
          case 2: return PING;
          case 3: return PONG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Cmd.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.soooner.ws.pb.Cmd.Type)
    }

    private int bitField0_;
    // required .com.soooner.ws.pb.Cmd.Type tp = 1;
    public static final int TP_FIELD_NUMBER = 1;
    private Type tp_;
    /**
     * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
     *
     * <pre>
     *type
     * </pre>
     */
    public boolean hasTp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
     *
     * <pre>
     *type
     * </pre>
     */
    public Type getTp() {
      return tp_;
    }

    // required int64 ct = 2;
    public static final int CT_FIELD_NUMBER = 2;
    private long ct_;
    /**
     * <code>required int64 ct = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    public boolean hasCt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 ct = 2;</code>
     *
     * <pre>
     * timestamp
     * </pre>
     */
    public long getCt() {
      return ct_;
    }

    // optional string txt = 3 [default = ""];
    public static final int TXT_FIELD_NUMBER = 3;
    private Object txt_;
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    public boolean hasTxt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    public String getTxt() {
      Object ref = txt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string txt = 3 [default = ""];</code>
     *
     * <pre>
     *support unknown message type
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTxtBytes() {
      Object ref = txt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.soooner.ws.pb.Meta meta = 4;
    public static final int META_FIELD_NUMBER = 4;
    private java.util.List<Meta> meta_;
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    public java.util.List<Meta> getMetaList() {
      return meta_;
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    public java.util.List<? extends MetaOrBuilder>
        getMetaOrBuilderList() {
      return meta_;
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    public int getMetaCount() {
      return meta_.size();
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    public Meta getMeta(int index) {
      return meta_.get(index);
    }
    /**
     * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
     */
    public MetaOrBuilder getMetaOrBuilder(
        int index) {
      return meta_.get(index);
    }

    private void initFields() {
      tp_ = Type.UNKNOWN;
      ct_ = 0L;
      txt_ = "";
      meta_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMetaCount(); i++) {
        if (!getMeta(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, tp_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, ct_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTxtBytes());
      }
      for (int i = 0; i < meta_.size(); i++) {
        output.writeMessage(4, meta_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tp_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ct_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTxtBytes());
      }
      for (int i = 0; i < meta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, meta_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Cmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Cmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Cmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Cmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Cmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Cmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Cmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Cmd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.soooner.ws.pb.Cmd}
     *
     * <pre>
     * bag id = 1
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Wraper.internal_static_com_soooner_ws_pb_Cmd_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Wraper.internal_static_com_soooner_ws_pb_Cmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Cmd.class, Builder.class);
      }

      // Construct using com.soooner.ws.pb.Wraper.Cmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMetaFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tp_ = Type.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        ct_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        txt_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          metaBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Wraper.internal_static_com_soooner_ws_pb_Cmd_descriptor;
      }

      public Cmd getDefaultInstanceForType() {
        return Cmd.getDefaultInstance();
      }

      public Cmd build() {
        Cmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Cmd buildPartial() {
        Cmd result = new Cmd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tp_ = tp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ct_ = ct_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.txt_ = txt_;
        if (metaBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            meta_ = java.util.Collections.unmodifiableList(meta_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Cmd) {
          return mergeFrom((Cmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Cmd other) {
        if (other == Cmd.getDefaultInstance()) return this;
        if (other.hasTp()) {
          setTp(other.getTp());
        }
        if (other.hasCt()) {
          setCt(other.getCt());
        }
        if (other.hasTxt()) {
          bitField0_ |= 0x00000004;
          txt_ = other.txt_;
          onChanged();
        }
        if (metaBuilder_ == null) {
          if (!other.meta_.isEmpty()) {
            if (meta_.isEmpty()) {
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMetaIsMutable();
              meta_.addAll(other.meta_);
            }
            onChanged();
          }
        } else {
          if (!other.meta_.isEmpty()) {
            if (metaBuilder_.isEmpty()) {
              metaBuilder_.dispose();
              metaBuilder_ = null;
              meta_ = other.meta_;
              bitField0_ = (bitField0_ & ~0x00000008);
              metaBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMetaFieldBuilder() : null;
            } else {
              metaBuilder_.addAllMessages(other.meta_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTp()) {
          
          return false;
        }
        if (!hasCt()) {
          
          return false;
        }
        for (int i = 0; i < getMetaCount(); i++) {
          if (!getMeta(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Cmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Cmd) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.soooner.ws.pb.Cmd.Type tp = 1;
      private Type tp_ = Type.UNKNOWN;
      /**
       * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
       *
       * <pre>
       *type
       * </pre>
       */
      public boolean hasTp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
       *
       * <pre>
       *type
       * </pre>
       */
      public Type getTp() {
        return tp_;
      }
      /**
       * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
       *
       * <pre>
       *type
       * </pre>
       */
      public Builder setTp(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.soooner.ws.pb.Cmd.Type tp = 1;</code>
       *
       * <pre>
       *type
       * </pre>
       */
      public Builder clearTp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tp_ = Type.UNKNOWN;
        onChanged();
        return this;
      }

      // required int64 ct = 2;
      private long ct_ ;
      /**
       * <code>required int64 ct = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public boolean hasCt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 ct = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public long getCt() {
        return ct_;
      }
      /**
       * <code>required int64 ct = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public Builder setCt(long value) {
        bitField0_ |= 0x00000002;
        ct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ct = 2;</code>
       *
       * <pre>
       * timestamp
       * </pre>
       */
      public Builder clearCt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ct_ = 0L;
        onChanged();
        return this;
      }

      // optional string txt = 3 [default = ""];
      private Object txt_ = "";
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public boolean hasTxt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public String getTxt() {
        Object ref = txt_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          txt_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTxtBytes() {
        Object ref = txt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          txt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public Builder setTxt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        txt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public Builder clearTxt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        txt_ = getDefaultInstance().getTxt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string txt = 3 [default = ""];</code>
       *
       * <pre>
       *support unknown message type
       * </pre>
       */
      public Builder setTxtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        txt_ = value;
        onChanged();
        return this;
      }

      // repeated .com.soooner.ws.pb.Meta meta = 4;
      private java.util.List<Meta> meta_ =
        java.util.Collections.emptyList();
      private void ensureMetaIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          meta_ = new java.util.ArrayList<Meta>(meta_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Meta, Meta.Builder, MetaOrBuilder> metaBuilder_;

      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public java.util.List<Meta> getMetaList() {
        if (metaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(meta_);
        } else {
          return metaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public int getMetaCount() {
        if (metaBuilder_ == null) {
          return meta_.size();
        } else {
          return metaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Meta getMeta(int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);
        } else {
          return metaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder setMeta(
          int index, Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.set(index, value);
          onChanged();
        } else {
          metaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder setMeta(
          int index, Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.set(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder addMeta(Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(value);
          onChanged();
        } else {
          metaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder addMeta(
          int index, Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetaIsMutable();
          meta_.add(index, value);
          onChanged();
        } else {
          metaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder addMeta(
          Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder addMeta(
          int index, Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.add(index, builderForValue.build());
          onChanged();
        } else {
          metaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder addAllMeta(
          Iterable<? extends Meta> values) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          super.addAll(values, meta_);
          onChanged();
        } else {
          metaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          metaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Builder removeMeta(int index) {
        if (metaBuilder_ == null) {
          ensureMetaIsMutable();
          meta_.remove(index);
          onChanged();
        } else {
          metaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Meta.Builder getMetaBuilder(
          int index) {
        return getMetaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public MetaOrBuilder getMetaOrBuilder(
          int index) {
        if (metaBuilder_ == null) {
          return meta_.get(index);  } else {
          return metaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public java.util.List<? extends MetaOrBuilder>
           getMetaOrBuilderList() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(meta_);
        }
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Meta.Builder addMetaBuilder() {
        return getMetaFieldBuilder().addBuilder(
            Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public Meta.Builder addMetaBuilder(
          int index) {
        return getMetaFieldBuilder().addBuilder(
            index, Meta.getDefaultInstance());
      }
      /**
       * <code>repeated .com.soooner.ws.pb.Meta meta = 4;</code>
       */
      public java.util.List<Meta.Builder>
           getMetaBuilderList() {
        return getMetaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Meta, Meta.Builder, MetaOrBuilder>
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Meta, Meta.Builder, MetaOrBuilder>(
                  meta_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.soooner.ws.pb.Cmd)
    }

    static {
      defaultInstance = new Cmd(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.soooner.ws.pb.Cmd)
  }

  public interface MetaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.soooner.ws.pb.Meta.Type tp = 1;
    /**
     * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
     */
    boolean hasTp();
    /**
     * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
     */
    Meta.Type getTp();

    // required string txt = 2;
    /**
     * <code>required string txt = 2;</code>
     */
    boolean hasTxt();
    /**
     * <code>required string txt = 2;</code>
     */
    String getTxt();
    /**
     * <code>required string txt = 2;</code>
     */
    com.google.protobuf.ByteString
        getTxtBytes();
  }
  /**
   * Protobuf type {@code com.soooner.ws.pb.Meta}
   *
   * <pre>
   * meta, add invisible payload to message &amp; command
   * </pre>
   */
  public static final class Meta extends
      com.google.protobuf.GeneratedMessage
      implements MetaOrBuilder {
    // Use Meta.newBuilder() to construct.
    private Meta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Meta(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Meta defaultInstance;
    public static Meta getDefaultInstance() {
      return defaultInstance;
    }

    public Meta getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Meta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Type value = Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                tp_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              txt_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wraper.internal_static_com_soooner_ws_pb_Meta_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wraper.internal_static_com_soooner_ws_pb_Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Meta.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Meta> PARSER =
        new com.google.protobuf.AbstractParser<Meta>() {
      public Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meta(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Meta> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.soooner.ws.pb.Meta.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0, 0),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Meta.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.soooner.ws.pb.Meta.Type)
    }

    private int bitField0_;
    // required .com.soooner.ws.pb.Meta.Type tp = 1;
    public static final int TP_FIELD_NUMBER = 1;
    private Type tp_;
    /**
     * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
     */
    public boolean hasTp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
     */
    public Type getTp() {
      return tp_;
    }

    // required string txt = 2;
    public static final int TXT_FIELD_NUMBER = 2;
    private Object txt_;
    /**
     * <code>required string txt = 2;</code>
     */
    public boolean hasTxt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string txt = 2;</code>
     */
    public String getTxt() {
      Object ref = txt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          txt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string txt = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTxtBytes() {
      Object ref = txt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        txt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tp_ = Type.UNKNOWN;
      txt_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, tp_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTxtBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tp_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTxtBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Meta prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.soooner.ws.pb.Meta}
     *
     * <pre>
     * meta, add invisible payload to message &amp; command
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Wraper.internal_static_com_soooner_ws_pb_Meta_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Wraper.internal_static_com_soooner_ws_pb_Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Meta.class, Builder.class);
      }

      // Construct using com.soooner.ws.pb.Wraper.Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tp_ = Type.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        txt_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Wraper.internal_static_com_soooner_ws_pb_Meta_descriptor;
      }

      public Meta getDefaultInstanceForType() {
        return Meta.getDefaultInstance();
      }

      public Meta build() {
        Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Meta buildPartial() {
        Meta result = new Meta(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tp_ = tp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.txt_ = txt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Meta) {
          return mergeFrom((Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Meta other) {
        if (other == Meta.getDefaultInstance()) return this;
        if (other.hasTp()) {
          setTp(other.getTp());
        }
        if (other.hasTxt()) {
          bitField0_ |= 0x00000002;
          txt_ = other.txt_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTp()) {
          
          return false;
        }
        if (!hasTxt()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Meta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Meta) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.soooner.ws.pb.Meta.Type tp = 1;
      private Type tp_ = Type.UNKNOWN;
      /**
       * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
       */
      public boolean hasTp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
       */
      public Type getTp() {
        return tp_;
      }
      /**
       * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
       */
      public Builder setTp(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.soooner.ws.pb.Meta.Type tp = 1;</code>
       */
      public Builder clearTp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tp_ = Type.UNKNOWN;
        onChanged();
        return this;
      }

      // required string txt = 2;
      private Object txt_ = "";
      /**
       * <code>required string txt = 2;</code>
       */
      public boolean hasTxt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string txt = 2;</code>
       */
      public String getTxt() {
        Object ref = txt_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          txt_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string txt = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTxtBytes() {
        Object ref = txt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          txt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string txt = 2;</code>
       */
      public Builder setTxt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        txt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string txt = 2;</code>
       */
      public Builder clearTxt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        txt_ = getDefaultInstance().getTxt();
        onChanged();
        return this;
      }
      /**
       * <code>required string txt = 2;</code>
       */
      public Builder setTxtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        txt_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.soooner.ws.pb.Meta)
    }

    static {
      defaultInstance = new Meta(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.soooner.ws.pb.Meta)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_soooner_ws_pb_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_soooner_ws_pb_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_soooner_ws_pb_Cmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_soooner_ws_pb_Cmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_soooner_ws_pb_Meta_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_soooner_ws_pb_Meta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014wraper.proto\022\021com.soooner.ws.pb\"\267\001\n\003Ms" +
      "g\022\r\n\005event\030\001 \002(\t\0220\n\002tp\030\002 \002(\0162\033.com.sooon" +
      "er.ws.pb.Msg.Type:\007UNKNOWN\022%\n\004meta\030\003 \003(\013" +
      "2\027.com.soooner.ws.pb.Meta\022\021\n\tuserCount\030\004" +
      " \001(\005\"5\n\004Type\022\013\n\007UNKNOWN\020\000\022\020\n\014CLIENT_EVEN" +
      "T\020\001\022\016\n\nUSER_COUNT\020\002\"\250\001\n\003Cmd\022\'\n\002tp\030\001 \002(\0162" +
      "\033.com.soooner.ws.pb.Cmd.Type\022\n\n\002ct\030\002 \002(\003" +
      "\022\r\n\003txt\030\003 \001(\t:\000\022%\n\004meta\030\004 \003(\0132\027.com.sooo" +
      "ner.ws.pb.Meta\"6\n\004Type\022\013\n\007UNKNOWN\020\000\022\r\n\tH" +
      "ANDSHAKE\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\"R\n\004Meta\022(",
      "\n\002tp\030\001 \002(\0162\034.com.soooner.ws.pb.Meta.Type" +
      "\022\013\n\003txt\030\002 \002(\t\"\023\n\004Type\022\013\n\007UNKNOWN\020\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_soooner_ws_pb_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_soooner_ws_pb_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_soooner_ws_pb_Msg_descriptor,
              new String[] { "Event", "Tp", "Meta", "UserCount", });
          internal_static_com_soooner_ws_pb_Cmd_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_soooner_ws_pb_Cmd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_soooner_ws_pb_Cmd_descriptor,
              new String[] { "Tp", "Ct", "Txt", "Meta", });
          internal_static_com_soooner_ws_pb_Meta_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_soooner_ws_pb_Meta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_soooner_ws_pb_Meta_descriptor,
              new String[] { "Tp", "Txt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
